### ISSUE TITLE
Error 0x5380C3

### ISSUE THREAD

**Issue by sonicfan0607** [goodidea82/SAxVCxLC#1]
Error 0x5380C3

**Comment by goodidea82** [comment]
"Error 0x5380C3" does not mean anything to me. I don't know what you did and when exactly it occured. 

The preferable page for communication is this one at the moment: http://gtaforums.com/topic/813938-saxvcxlc-vc-and-lc-in-san-andreas/

**Comment by sonicfan0607** [comment]
im sorry

**Comment by goodidea82** [comment]
Added description in Readme.md in the section Troubleshooting
Also see here: http://gtaforums.com/topic/813938-saxvcxlc-vc-and-lc-in-san-andreas/?p=1069668668
